name: Code checks

on: [push]

env:
  POETRY_VERSION: 1.8.5

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "${{env.POETRY_VERSION}}"

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yaml
          micromamba-version: latest
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'

      - name: Install the library
        shell: micromamba-shell {0}
        run: poetry install -v | poetry install -vvv

      - name: Test the library
        shell: micromamba-shell {0}
        run: |
          poetry run ruff format --check --diff
          poetry run ruff check
          poetry run mypy
          poetry run pytest
