name: Code checks

on: [push]

env:
  POETRY_VERSION: 1.8.5

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "${{env.POETRY_VERSION}}"

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yaml
          micromamba-version: latest
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'

      - name: Get full Python version
        id: full-python-version
        shell: micromamba-shell {0
        run: echo "version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")" >> $GITHUB_OUTPUT

      - name: Set up cache
        uses: actions/cache@v4
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
  
      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        shell: micromamba-shell {0
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv

      - name: Install the library
        shell: micromamba-shell {0}
        run: poetry install -v | poetry install -vvv

      - name: Test the library
        shell: micromamba-shell {0}
        run: |
          poetry run ruff format --check --diff
          poetry run ruff check
          poetry run mypy
          poetry run pytest
